spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=system
spring.datasource.password=anhlaso1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Optional
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=ZGVtby1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtdGhpcy10by1hLXN0cm9uZy1iYXNlNjQta2V5
app.jwt.expiration-ms=86400000


